feat(LLC-5575): detailed exoplayer exceptions
surfstudio/plugins pull request #19
Opened 2022-04-20 10:07 UTC by tinted-knight

Детализация ошибок для Андроида

Всё-таки добавил отдельное поле во избежание

До было так
```
Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error
```

После оформил как json, чтоб при желании можно было распарсить
```
{
  "errorType": "TYPE_SOURCE",
  "message": "Source error",
  "dataSourceType": "1",
  "dataSourceTypeDescription": "TYPE_OPEN",
  "uri": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "rawException": "com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect"
}
```

Live-метрики. Привер с дропами на 1080p качестве на девайсе (на HLS)

https://user-images.githubusercontent.com/25702530/164449243-cc9ef9f6-7791-430f-9dd5-54c0fd36eb02.mp4

2022-04-21 12:02 UTC, plastb1r commented on packages/video_player/video_player/lib/video_player.dart
> +  final int framesBeenDropped;
а для iOS вообще нет вариантов по метрикам? как-то подрубиться и так же слушать. или пока только андроид смотрел

2022-04-22 06:41 UTC, mpkander approved these changes

2022-04-22 07:11 UTC, tinted-knight commented on packages/video_player/video_player/lib/video_player.dart
> +  final int framesBeenDropped;
Хороший вопрос. Но в сторону ios пока вообще не смотрел.

2022-04-24 11:54 UTC, plastb1r requested changes

2022-04-24 11:54 UTC, plastb1r commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/HoleErrorBuilder.java
> +public class HoleErrorBuilder {
Можешь здесь доки сыпануть, плез

2022-04-24 11:54 UTC, plastb1r commented on packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
> +  playbackMetrics,
и сюда для красоты

2022-04-24 11:55 UTC, plastb1r approved these changes

2022-05-01 11:13 UTC, plastb1r commented
А мы можем теперь из ошибки точно понимать, что она возникла из-за отключения инета?
Тк сейчас для иос Маша добавила, флаг, который точно говорит, что ошибка есть, и она из-за инета (hasInternetError). Может сделать подобное и для андроида, чтобы данные не затирались на нем

<img width="503" alt="Screenshot 2022-05-01 at 14 12 55" src="https://user-images.githubusercontent.com/33830654/166143487-af5ed1a8-c83d-4e0e-881c-a707987aaad9.png">

2022-05-06 09:35 UTC, merged