Feature/buffering
surfstudio/plugins pull request #20
Opened 2022-05-12 12:16 UTC by mpkander

2022-05-13 10:54 UTC, tinted-knight commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +  private static DefaultLoadControl createDefaultLoadControlBy(Messages.BufferMessage bufferMessage) {
Правильно понимаю, что это штука пытается взять из дарта (если мы передали), а иначе ставит дефотлные значения?

2022-05-13 10:57 UTC, tinted-knight commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +    double forwardBufferDuration = 0.0;
А вот этот 0.0 - это он сам будет решать сколько (какое-то дефолтное у AVPlayer) или прям ноль?

2022-05-13 11:04 UTC, tinted-knight requested changes

2022-05-13 11:04 UTC, tinted-knight commented on packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
> +  final Duration? bufferForPlaybackAfterRebuffer;
Вот это всё круто со ссылочками ❤️

2022-05-13 13:24 UTC, plastb1r commented
а мы планируем попробовать контрибьютить этим? что-то упустил
А то модификации поверх видеоконтроллера все увеличиваются, и ведь в дальнейшем, будет больнее переходить на свежую версию

2022-05-13 13:24 UTC, plastb1r approved these changes

2022-05-13 13:28 UTC, vasbaza approved these changes

2022-05-16 07:31 UTC, mpkander commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +  private static DefaultLoadControl createDefaultLoadControlBy(Messages.BufferMessage bufferMessage) {
Да, всё так 

У меня привычка чистые функции делать статиками, не вижу тут проблем

2022-05-16 07:32 UTC, mpkander commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +    double forwardBufferDuration = 0.0;
Да, тут 0.0 это аналог nil для примитивного типа

2022-05-16 07:34 UTC, mpkander commented
@plastb1r Это способ поддержки плеера, который выбрали не мы. Контрибьют это долгий процесс, я попробую оформить его в +- таком же виде, но новые фичи очень долго согласуются с командой флаттера. Я хотя бы попробую предложить, но сначала в приоритете наши проектные задачи

2022-05-16 08:36 UTC, tinted-knight approved these changes

2022-06-01 08:34 UTC, merged